#!/usr/bin/env node
/**
 * Editorial inventory and structural risk assessment for Kabin Agent's bilingual site.
 * Heuristics identify pages needing HUMAN AIDA/PAS/SSS/STRINGS review.
 * They do not score persuasion quality or prove framework compliance.
 * Usage: node scripts/audit-copy.mjs [output-directory]
 */
import fs from "node:fs";
import path from "node:path";

const root=process.cwd(), out=process.argv[2]||"editorial-audit-output";
const names={en:["Platform","Solutions","Marketplace","Developers","Resources","Company"],vi:["Nền tảng","Giải pháp","Marketplace","Nhà phát triển","Tài nguyên","Công ty"]};
const paths=["docs/content"];
const files=fs.readdirSync(path.join(root,paths[0])).filter(f=>/\.(?:en|vi)\.md$/.test(f)).sort();
const rows=[];
const wordCount=s=>(s.match(/[\p{L}\p{N}]+/gu)||[]).length;
function assign(route){
  if(route==="/")return ["AIDA","Conversion-oriented overview"];
  if(/^\/legal\//.test(route))return ["FACTUAL","Accuracy/privacy/legal completeness (not persuasion)"];
  if(/^\/solutions\//.test(route))return ["PAS + SSS","Role-specific pain and illustrative scenario"];
  if(/^\/marketplace\//.test(route)||route==="/marketplace/")return ["AIDA + PAS","Capacity discovery, comparison and safe next action"];
  if(/^\/developers\//.test(route)||route==="/developers/"||route==="/docs/")return ["STRINGS","Teach with concrete contracts/examples, avoid invented API claims"];
  if(/^\/(?:resources|blog|faq|updates|use-cases|case-studies)\//.test(route))return ["STRINGS","Give reusable teaching value and citations where needed"];
  if(/^\/company\//.test(route)||route==="/company/")return ["SSS + STRINGS","Authentic brand story, values and credibility without fake customer stories"];
  if(/^\/platform\//.test(route)||route==="/platform/")return ["PAS + AIDA","Technical tension, architecture, benefits and realistic next step"];
  if(/^\/(?:contact|partners|support)\//.test(route))return ["AIDA / FACTUAL","Clarity, trust and low-friction contact"];
  return ["STRINGS","Educational explanation"];
}
for(const f of files){
 const body=fs.readFileSync(path.join(root,paths[0],f),"utf8");
 const locale=f.endsWith(".vi.md")?"vi":"en";
 const route=body.match(/^route:\s*(\S+)/m)?.[1];
 if(!route){rows.push({file:f,error:"missing route frontmatter"});continue;}
 const htmlFile=route==="/"
  ?"index.html"
  :path.posix.join(route.replace(/^\/|\/$/g,""),"index.html");
 const htmlPath=path.join(root,htmlFile);
 const html=fs.existsSync(htmlPath)?fs.readFileSync(htmlPath,"utf8"):"";
 const lead=body.replace(/^---[\s\S]*?---\s*/,"")
   .split(/^## (?:Related navigation|Điều hướng liên quan|Contact|Liên hệ|Corporate identity|Nhận diện doanh nghiệp|Editorial constraints|Ghi chú biên tập)/m)[0];
 const coreWords=wordCount(lead);
 const generatedDoc=/^## (?:Positioning|Định vị)[\s\S]*?^## (?:Content pillars|Các điểm nội dung)/m.test(body);
 const genericVisual=html.includes("class=\"art-target\"")&&html.includes("art-ring ring-one");
 const genericCTA=/Explore the approach|Khám phá nội dung/.test(html);
 const [framework,goal]=assign(route);
 const issues=[];
 if(!html)issues.push("MISSING_HTML");
 if(generatedDoc)issues.push("TEMPLATE_EDITORIAL");
 if(genericVisual)issues.push("DUPLICATED_VISUAL");
 if(genericCTA)issues.push("GENERIC_CTA");
 if(coreWords<130&&!/^\/legal\//.test(route))issues.push("THIN_CORE_COPY");
 const uniqueHook=(html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/)?.[1]||"").replace(/<[^>]+>/g," ").trim();
 const evidence=/(?:\bexample\b|\bscenario\b|\bfor instance\b|\bsteps? to\b|ví dụ|tình huống|minh họa|mẫu cụ thể|illustrative)/i.test(lead);
 if(!evidence&&!/^\/legal\//.test(route))issues.push("NO_CONCRETE_EXAMPLE_FLAG");
 rows.push({file:f,route,locale,coreWords,framework,goal,issues,headline:uniqueHook});
}
rows.sort((a,b)=>a.route.localeCompare(b.route)||a.locale.localeCompare(b.locale));
const group=route=>{
 const one=route.split("/").filter(Boolean)[0]||"home";
 return ["blog","faq","docs","updates","use-cases","case-studies","support"].includes(one)?"resources":one==="contact"||one==="partners"||one==="legal"?"company":one;
};
const counter={};for(const r of rows)for(const k of r.issues||[])counter[k]=(counter[k]||0)+1;
const pairs=new Map();
for(const r of rows){if(!r.route)continue;const key=r.route.replace(/^\/vi\//,"/");const e=pairs.get(key)||{};e[r.locale]=r;pairs.set(key,e);}
const missingPairs=[...pairs].filter(([k,v])=>!v.en||!v.vi).map(([k])=>k);
const grouped={};for(const r of rows){const g=group(r.route||"/");(grouped[g]||=[]).push(r);}
const column=(s)=>String(s||"").replace(/\|/g,"\\/").replace(/\n/g," ");
const enRows=rows.filter(r=>r.locale==="en");
let md="# Kabin Agent | Full-site editorial inventory\n\n";
md+="**Generated by** \`scripts/audit-copy.mjs\`. This is a structural triage, **not** a human claim that a page passes or fails a persuasion framework.\\n\\n".replaceAll("\\n","\n");
md+=\`Total editorial files: **\${rows.length}**; EN/VI pairs: **\${pairs.size}**; missing pairs: **\${missingPairs.length}**.\\n\\n\`.replaceAll("\\n","\n");
md+="## Evidence from complete local source scan\n\n";
md+="| Finding | Files flagged | Interpretation |\n|---|---:|---|\n";
for(const [key,label] of Object.entries({
  TEMPLATE_EDITORIAL:"Recurring Positioning / three content-pillar document outline",
  DUPLICATED_VISUAL:"Identical radial-node hero illustration",
  GENERIC_CTA:"Same generic Explore CTA",
  THIN_CORE_COPY:"Fewer than 130 word tokens of primary editorial content",
  NO_CONCRETE_EXAMPLE_FLAG:"No immediately detectable worked example; **manual verification needed**",
  MISSING_HTML:"Markdown without matching HTML"
}))md+=\`| \${label} | \${counter[key]||0} | \${key} |\\n\`.replaceAll("\\n","\n");
md+="\n## Editorial standards\n\n";
md+="- **AIDA**: specific attention hook; relevant interest; earned desire (clear outcome with evidence); precise action.\n";
md+="- **PAS**: exact reader problem; honest consequence/tension; credible solution tied directly to the problem.\n";
md+="- **SSS**: recognizable *role/scenario* (never a fabricated testimonial), meaningful challenge, credible solution and its limits.\n";
md+="- **STRINGS**: Share useful context; Teach with worked examples; Reward with reusable insight; Intrigue with a substantive question; Nurture trust by disclosing limits; Generate a relevant next step. Published variations differ, so this is the working editorial rubric.\n";
md+="- **FACTUAL**: privacy/terms/cookies pages require factual accuracy, ownership, processing boundaries and legal review, not a conversion formula.\n";
md+="- **Hard gate**: no invented numbers, clients, testimonials, certifications, available endpoints, current prices, published SDKs or transactions.\n\n";
md+="## Group inventory\n\n| Group | Localized pages | Default narrative | Priority |\n|---|---:|---|---|\n";
for(const [g,v] of Object.entries(grouped))md+=\`| \${g} | \${v.length} | \${v[0]?.framework||""} | \${["marketplace","solutions","developers","platform"].includes(g)?"P1":"P2"} |\\n\`.replaceAll("\\n","\n");
md+="\n## URL-by-URL editorial worklist\n\n| Route (EN) | Recommended narrative | EN core words | VI core words | Deficits (EN / VI) | Editorial next step |\n|---|---|---:|---:|---|---|\n";
for(const [key,v] of pairs){
const count=it=>it?.coreWords??"missing";
md+=\`| \${column(key)} | \${column(v.en?.framework||v.vi?.framework)} | \${count(v.en)} | \${count(v.vi)} | \${column((v.en?.issues||[]).join(", "))} / \${column((v.vi?.issues||[]).join(", "))} | Write page-specific brief, hook, narrative sequence, evidence constraints and CTA; update both Markdown + HTML |\\n\`.replaceAll("\\n","\n");
}
md+="\n## Human editorial review required before claiming PASS\n\n";
md+="Every page must answer: **who is reading, what job are they trying to finish, what obstructs them, what exactly changes, why is the claim credible, what should they do next?** Editors must review each line in EN and VI. The heuristic flags cannot grade truth, originality, emotional persuasion, copy rhythm or translation quality.\n";
md+="\n## Next build order\n\n";
md+="1. Marketplace overview + category pages: AIDA/PAS, category-specific capacity inspection visuals and comparison semantics.\n";
md+="2. Solutions overview + role pages: PAS, with SSS only when the scenario is explicitly hypothetical or sourced from approved real case materials.\n";
md+="3. Developers overview + technical pages: STRINGS teaching, sample manifests clearly illustrative, limitations and no fabricated endpoints.\n";
md+="4. Platform/Company/Resources: authentic architecture, company narrative, genuinely useful learning resources.\n";
md+="5. Factual/legal pages: separately reviewed completeness and correctness; no marketing formulas.\n";
fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,"full-site-editorial-audit.md"),md);
const csv=["route,locale,framework,core_words,issues,source_md,source_html",...rows.map(r=>[r.route,r.locale,r.framework,r.coreWords,(r.issues||[]).join(";"),"docs/content/"+r.file,r.route==="/"?"/index.html":r.route+"index.html"].map(x=>'"'+String(x||"").replaceAll('"','""')+'"').join(","))].join("\n");
fs.writeFileSync(path.join(out,"copy-inventory.csv"),csv);
fs.writeFileSync(path.join(out,"copy-inventory.json"),JSON.stringify({summary:{rows:rows.length,pairs:pairs.size,missingPairs,counter},rows},null,2));
console.log(JSON.stringify({rows:rows.length,pairs:pairs.size,missingPairs,counter,output:out},null,2));
if(missingPairs.length||rows.some(r=>r.error))process.exitCode=1;
